import "./globals.css";
import type { Metadata } from "next";
import { Providers } from "./providers";
import Alerts from "@/components/common/alerts/Alerts";

export const metadata: Metadata = {
  title: {
    template: "%s | Livecart",
    default: "Livecart",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Alerts />
          {children}
        </Providers>
      </body>
    </html>
  );
}
